name: 'nexus-supply-chain-ops'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

# FORCE everything in this project to use the 'workspace' catalog
vars:
  databricks_catalog: workspace

models:
  nexus-supply-chain-ops:
    +catalog: workspace           # The primary Unity Catalog name
    +schema: supply_chain_analytics
    +materialized: view           # Default for all models
    
    # Specific override for your Gold/Fact layer
    fct_shipping_performance:
      +materialized: table
      +file_format: delta