name: 'nexus-supply-chain-ops'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nexus-supply-chain-ops:
    +materialized: view