name: 'nexus-supply-chain-ops' # Changed to dashes
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# This section MUST match the name at the top
models:
  nexus-supply-chain-ops: # Changed to dashes
    staging:
      +materialized: view