name: 'nexus-supply-chain-ops'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]

# THIS IS THE KEY: Global variable override
vars:
  catalog: workspace

models:
  nexus-supply-chain-ops:
    +catalog: workspace
    +database: workspace
    +schema: supply_chain_analytics

# Add this section to force tests to look in the same place
tests:
  nexus-supply-chain-ops:
    +catalog: workspace
    +database: workspace
    +schema: supply_chain_analytics