name: 'nexus-supply-chain-ops'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

# FORCE everything in this project to use the 'workspace' catalog
vars:
  databricks_catalog: workspace

models:
  nexus-supply-chain-ops:
    +catalog: workspace          # Added this - Unity Catalog specific
    +database: workspace         # Kept this for safety
    +schema: supply_chain_analytics
    staging:
      +materialized: view