name: 'nexus-supply-chain-ops'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

models:
  nexus-supply-chain-ops:
    +database: workspace           # Forces Unity Catalog 'workspace'
    +schema: supply_chain_analytics
    +materialized: view