version: 2

models:
  - name: int_shipments
    columns:
      - name: shipment_item_id
        tests:
          - unique
          - not_null

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - unique
          - not_null

  - name: fct_shipping_performance
    description: "Gold Layer: Final fact table optimized for Star Schema reporting."
    columns:
      - name: shipment_item_id
        tests:
          - unique
          - not_null

      - name: product_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_products')
                field: product_key

      - name: location_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_locations')
                field: location_key

      - name: shipping_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_shipping_info')
                field: shipping_key

      - name: order_date_key
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_date')
                field: date_key