name: dbt_CI_CD_Governance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install dbt-databricks
          dbt deps

      - name: Authenticate and Debug
        env:
          DBT_HOST: ${{ secrets.DBT_HOST }}
          DBT_HTTP_PATH: ${{ secrets.DBT_HTTP_PATH }}
          DBT_TOKEN: ${{ secrets.DBT_TOKEN }}
        run: |
          # We create a temporary profile for the CI runner
          mkdir -p ~/.dbt
          echo "nexus_supply_chain:
            outputs:
              dev:
                type: databricks
                catalog: workspace
                schema: supply_chain_analytics
                host: $DBT_HOST
                http_path: $DBT_HTTP_PATH
                token: $DBT_TOKEN
                threads: 1
            target: dev" > ~/.dbt/profiles.yml

      - name: dbt Debug & Parse
        run: |
          dbt debug # Tests the connection to Databricks
          dbt parse # Validates the SQL and Lineage